### ISSUE TITLE
Use link /overview instead /login.html to sync cookies on error

### ISSUE THREAD

**Issue by tolmachev-pravo** [deimosowen/TeamCity-Pull-Request-Builder#18]
Сейчас при отсутствии cookies ссылка ведет на страницу логина, и кажется, что всегда нужно вводить логина и пароль. Думаю, что оптимальнее кидать на страницу /overview. Если актуального логина нет, то оно само перекинет на логин, в остальном случае подцепит актуальные cookies.

**Comment by deimosowen** [comment]
После смены метода авторизации в #16 проблема быть недолжно.
