### ISSUE TITLE
 Problem with the right panel scaling

### ISSUE THREAD

**Issue by tolmachev-pravo** [deimosowen/TeamCity-Pull-Request-Builder#46]
📌 **Current Behavior:** 
Панель справа не скролится. При использовании расширения часть информации теперь теряется.
Разрешение экрана 1920х1080

![image](https://github.com/deimosowen/TeamCity-Pull-Request-Builder/assets/62241382/c441d5bc-fd83-41ea-b08d-d118ebeb0a04)

🎯 **Desired Behavior:** 
Вся информация отображается на экране.

**Comment by deimosowen** [comment]
Видимо у гитлаба было обновление и зафиксировали панель, надо будет разблокировать
