### ISSUE TITLE
Обработка завершения сессии Teamcity

### ISSUE THREAD

**Issue by tolmachev-pravo** [deimosowen/TeamCity-Pull-Request-Builder#5]
**PROBLEM** 📕
- Используемая сессия Teamcity тоже может протухать или завершаться.
- В таком случае мы просто получаем пустой список сборок
![image](https://user-images.githubusercontent.com/62241382/228745775-ac1ba63b-619b-441e-8624-f608bb5f871f.png)

**GOAL** 📗
- Добавить возможность видеть причину неотображения доступных сборок
- Добавить колесико прогрузки списка сборок
- В случае если проблема с сессией Teamcity, то иметь возможность продлить сессию из github, хотя бы просто переходом по ссылке в Teamcity.

**Comment by deimosowen** [comment]
Добавлена проверка на активную авторизацию в TC
![image](https://user-images.githubusercontent.com/3768554/229272615-6b5c5230-c9b9-4018-9aac-af7a0e3a3dfb.png)
